name: GitHub Container Registry

on:
  push:
    branches: [ master ]

jobs:
  GHCR:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: docker build -t go-docker-mqtt-ubuntu-env .

    - name: Login to GitHub Container Registry
      uses: docker/login-action@master
      with:
        registry: ghcr.io
        username: arduinobot
        password: ${{ secrets.CR_PAT }}

    - name: Publish
      run: |
        docker tag go-docker-mqtt-ubuntu-env ghcr.io/arduino/go-docker-mqtt-ubuntu-env:latest
        docker push ghcr.io/arduino/go-docker-mqtt-ubuntu-env
